# 2017-09-07 13:00:19
li $23 97 
li $22 97 
li $21 0 
beqz $20 label_0_ 
nop 
beqz $19 label_0_ 
nop 
li $21 1 
label_0_: 
li $18 89 
li $17 0 
beqz $21 label_1_ 
nop 
beqz $16 label_1_ 
nop 
li $17 1 
label_1_: 
# Generated by move temp 
move $15 $23 
# Generated by move temp 
move $14 $15 
move $19 $2 
move $22 $4 
li $2 11 
move $4 $14 
syscall 
move $2 $19 
move $4 $19 
